-- SolarShift OS — Phase 1 core data. No scoring engine is defined here.
create extension if not exists pgcrypto;

-- Supabase starter projects can already provide public.profiles. It remains
-- the identity source of truth; this migration only references it.
do $$ begin create type public.solarshift_role as enum ('ADMIN','SOLARSHIFT','MANDATAIRE','EXPERT','CLIENT','INVESTOR','INSTITUTION'); exception when duplicate_object then null; end $$;
do $$ begin create type public.project_status as enum ('LEAD','QUALIFICATION','DATA_COLLECTION','ANALYSIS','VALIDATION','PRE_FINANCEABLE','FINANCEABLE','CONTRACTING','EXECUTION','OPERATING','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.validation_state as enum ('UNKNOWN','PENDING','VALIDATED','REJECTED'); exception when duplicate_object then null; end $$;
create table public.organizations (id uuid primary key default gen_random_uuid(), legal_name text not null, created_at timestamptz not null default now());
create table public.organization_memberships (organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.solarshift_role not null, created_at timestamptz not null default now(), primary key (organization_id,user_id,role));
create table public.clients (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), legal_name text not null, siren text, siret text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.contacts (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.clients(id) on delete cascade, full_name text not null, email text, role_title text, created_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), client_id uuid references public.clients(id), project_reference text not null unique, name text not null, status public.project_status not null default 'LEAD', address text, postal_code text, city text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_access_grants (project_id uuid not null references public.projects(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.solarshift_role not null, created_at timestamptz not null default now(), primary key(project_id,user_id,role));
create table public.documents (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, document_type text not null, file_name text not null, storage_path text not null unique, checksum text, processing_status text not null default 'PENDING', uploaded_by uuid references public.profiles(id), uploaded_at timestamptz not null default now());
create table public.project_parameters (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, parameter_code text not null check (parameter_code ~ '^[A-H][0-9]{2}$'), value_numeric numeric, value_text text, value_boolean boolean, value_date date, value_json jsonb, unit text, source_type text not null, confidence_level text not null check (confidence_level in ('L0','L1','L2','L3','L4','L5')), validation_status public.validation_state not null default 'UNKNOWN', version integer not null default 1 check(version > 0), supersedes_id uuid references public.project_parameters(id), created_at timestamptz not null default now(), created_by uuid references public.profiles(id), unique(project_id,parameter_code,version));
create table public.evidences (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, parameter_id uuid not null references public.project_parameters(id), document_id uuid references public.documents(id), extracted_value jsonb, evidence_date date, page_reference text, excerpt text, extraction_method text not null, confidence numeric check(confidence between 0 and 1), created_at timestamptz not null default now());
create table public.validations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, entity_type text not null, entity_id uuid not null, previous_status text, new_status text not null, validated_by uuid not null references public.profiles(id), comment text, validated_at timestamptz not null default now());
create table public.contradictions (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, parameter_code text not null, evidence_a_id uuid not null references public.evidences(id), evidence_b_id uuid not null references public.evidences(id), severity text not null check(severity in ('LOW','MEDIUM','HIGH','CRITICAL')), status text not null default 'OPEN', resolved_by uuid references public.profiles(id), resolved_at timestamptz, check(evidence_a_id <> evidence_b_id));
create table public.audit_log (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete set null, entity_type text not null, entity_id uuid not null, action text not null, old_value jsonb, new_value jsonb, reason text, user_id uuid references public.profiles(id), created_at timestamptz not null default now());

create function public.can_access_project(target_project uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists (select 1 from public.projects p join public.organization_memberships m on m.organization_id=p.organization_id where p.id=target_project and m.user_id=auth.uid()) or exists (select 1 from public.project_access_grants g where g.project_id=target_project and g.user_id=auth.uid()); $$;

alter table public.projects enable row level security; alter table public.documents enable row level security; alter table public.project_parameters enable row level security; alter table public.evidences enable row level security; alter table public.validations enable row level security; alter table public.contradictions enable row level security; alter table public.audit_log enable row level security;
create policy "project access" on public.projects for select using (public.can_access_project(id));
create policy "document access" on public.documents for select using (public.can_access_project(project_id));
create policy "parameter access" on public.project_parameters for select using (public.can_access_project(project_id));
create policy "evidence access" on public.evidences for select using (public.can_access_project(project_id));
create policy "validation access" on public.validations for select using (public.can_access_project(project_id));
create policy "contradiction access" on public.contradictions for select using (public.can_access_project(project_id));
create policy "audit access" on public.audit_log for select using (project_id is not null and public.can_access_project(project_id));
